name: Deploy on prod

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name:
        run: |
          echo "SSH_HOST=${{ secrets.SSH_HOST }}"
          echo "SSH_USER=${{ secrets.SSH_USER }}"

      - name: Deploy Over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.bashrc || source ~/.profile || source ~/.bash_profile
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd bms
            git pull origin production
            npm install -g pnpm
            npm install -g pm2
            pnpm install --frozen-lockfile
            pnpm build
            pm2 restart all
